language: ruby
rvm: 2.0.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - GIT_COMMITTER_NAME="Yusuke Kanda"
    - GIT_COMMITTER_EMAIL="uskanda@gmail.com"
    - GIT_AUTHOR_NAME="Yusuke Kanda"
    - GIT_AUTHOR_EMAIL="uskanda@gmail.com"
    - secure: "bW4IdS82UqSGmdpGUyqCFyU049t9h/+gwbIBeAgbKyN3aHjtgQQQSJbhVnbEGp6iTqTyVXmthdR3OiKyCwhGjk/VSPWIUIn274ksHKv48puIb5/wwA9GEpEE42jC9PiBaMkqoMFv+hAxGD1BJRDZqA+VBqI5S9qLcKjSBdutiGc="
